### ISSUE TITLE
"Help me choose" help link incorrect

### ISSUE THREAD

**Issue by alexmbaker** [Kyrodan/KeeAnywhere#19]
Very minor issue but the link looks like a test one...

![image](https://cloud.githubusercontent.com/assets/2808984/12662264/3ab6a548-c673-11e5-8b6c-e957366f8b44.png)

**Comment by Kyrodan** [comment]
Yes, you are right, I forgot to correct it.

The Windows credentials store saves your accounts secured and only
accessible by your logged in windows user. The other option saves your
accounts unsecured in KeePass configuration. You should choose the second
one only, if you would like to use KeePass portable e.g. On an USB drive.
The first option is the safest one.

Alex Baker <notifications@github.com> schrieb am Fr., 29. Jan. 2016 00:32:

**Comment by witeshadow** [comment]
Is there anyway to accomplish portability AND security? Perhaps using a 2nd database that stores the cloud info so a current main database can be retrieved?

**Comment by Kyrodan** [comment]
@witeshadow: Storing the credentials in a second database is not an option for me (it's a blacklistet feature because because it complicates the whole thing from a user's perspective. If you like this, you can use KeeCloud which implements exactly this - but currently only supports Dropbox). Beyond this restriction, we can continue this discussion - but please open a new issue for that.

**Comment by bjorndoublehorn** [comment]
> The other option saves your accounts unsecured in KeePass configuration.
Exactly where (in what file) is it saved?

**Comment by Kyrodan** [comment]
@bjorndoublehorn: see KeePass documentation at http://keepass.info/help/base/configuration.html
It depends on your configuration. Default for installed version is "Local" (C:\Users\<User Name>\AppData\Roaming\KeePass\KeePass.config.xml).
