### ISSUE TITLE
Dropbox: Error (400)

### ISSUE THREAD

**Issue by frdrc66** [Kyrodan/KeeAnywhere#191]
Hello,
I've built the 1.6.0-unstable version (using VS 2019), and when trying to add a Dropbox account, I get:

> Error (400)
> It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
> More details for developers
> Invalid client_id: "dummy".

Wrong generation?
TIA

**Comment by Kyrodan** [comment]
Hi do not provide a valid "client_id" for all the providers in the GitHub
source code.
You have to create your own ID's for testing purposes. In
"SrorageProviders\Dropbox\DropboxHelper.cs" you can find instructions at
the top of the file.

Am Mo., 25. Nov. 2019 um 00:38 Uhr schrieb frdrc66 <notifications@github.com

**Comment by frdrc66** [comment]
Hi Daniel,
Not sure I have understood the concept. I do not want to test the tool,
just use it. Because I couldn't find a workable version (compatible with
the last KeePass one), I tried to build it from Git... with no success so
far.
Thanks anyway for your answer, I will have a look at this DropboxHelper.cs
some day.

Le lun. 25 nov. 2019 à 08:24, Daniel Bölts <notifications@github.com> a
écrit :

**Comment by Kyrodan** [comment]
Current PLGX-release 1.5.1 is compatible with latest KeePass - I use it by
myself. DLL-Release is always a problem and works only with the exact
version of KeePass at time of creation.
You can compile the source code but it will not work out of the box because
I do not provide my app keys in GitHub.

frdrc66 <notifications@github.com> schrieb am Mo., 25. Nov. 2019, 09:30:

**Comment by frdrc66** [comment]
Do you mean that a non computer scientist who can't rebuild this DLL can't
use KeeAnywhere anymore after each KeePass release?!
Is there a HOWTO somewhere that explain which DLL to upgrade and/or where
to find it?
Thanks

Le lun. 25 nov. 2019 à 09:38, Daniel Bölts <notifications@github.com> a
écrit :

**Comment by Kyrodan** [comment]
What you describe are two different problems.

Problem 1:
DLL-Distribution is not compatible with Version x.y of KeePass.

The solution is to use the *PLGX-Distribution* of KeeAnywhere. This always
compatible with the mentioned KeePass-Version and all Versions above.
In my latest documentation I do not recommend DLL-Distribution anymore (
https://keeanywhere.de/use/installation).

Details for PLGX/DLL-Distribution:
* https://keepass.info/help/v2/plugins.html
* https://keepass.info/help/v2_dev/plg_index.html#plgx

Remark: If you get a "Compatibility-Error" if you were using the PLGX =>
then you maybe have another issue (like damaged config files). I will add
documentation to the Troubleshooting-Section shortly.

Problem 2:
In the source code I do not provide private keys for the communication with
the cloud providers. Most provides forbid to distribute the keys in public.
That means: You *can* compile the plugin, but you *cannot use* it. You can
create your own Provider-Keys and use it in *your* version of the source
code.
So, you are right: without some "compuer science knowledge" you are not
able to create a working copy of this plugin.
Please keep in mind: if you are not a computer scientist but willing to
deal with source code, then it is maybe a very high risk (because you maybe
do not really know, what you are doing).

Does this help you with your question?


Am Mo., 25. Nov. 2019 um 10:47 Uhr schrieb frdrc66 <notifications@github.com

**Comment by frdrc66** [comment]
>
> What you describe are two different problems.
>
> Problem 1:
> ...
> The solution is to use the *PLGX-Distribution* of KeeAnywhere...
>

Actually, this is what didn't work for me.
I've just (re)tried on another PC, and it works. I have to check again, at
home.

Problem 2:
> In the source code I do not provide private keys for the communication with
> the cloud providers...
>

Understood.

Does this help you with your question?
>

Yes, thank you Daniel.
