### ISSUE TITLE
Changelog opens each time when KeePass starts

### ISSUE THREAD

**Issue by ThirtySomething** [Kyrodan/KeeAnywhere#202]
Hi there,

on my system each time when I start KeePass, the changelog of KeeAnywhere is opened in the default browser.

My versions:
- KeePass 2.43
- KeeAnywhere 1.60
- OS Windows 10 Home 1909, Build 18363.535

Do you need any additional information for analysis? Please let me know.

**Comment by Kyrodan** [comment]
Hmm, I can not reproduce this.
Can you try this:
* open the KeeAnywhere Settings
* close the dialog
* close KeePass
* restart KeePass

Is it then still present?
If yes: 
* Is KeePass installed or partable? 
* Is it able to write to the KeePass config file?

What happens: 
if you start KeePass it checks, whetherthe current plugin version is different to the saved one in KePass Config. If you terminate KeePass the new version is written to the config file (or if you open and close the settings dialog with the Ok-Button). So I it always opens the ChangeLog, then it new version is maybe never written to the config file.

**Comment by Kyrodan** [comment]
Hmm, maybe try to open and close the settings dialog twice before terminating KeePass.

**Comment by justinvoelker** [comment]
Same issue here. It appears to be a conflict in config files (I have two: one in Program Files and one in AppData). The config in Program Files has the old KeeAnywhere version whereas the config in AppData has the newest, correct version of 1.6.0.0.

I believe my issue stems from using KeePass portable a while ago and, when installing it normally, simply moving the config into the program directory. It looks like the config in the Program Files has not been updated in a while but the config in AppData is otherwise up-to-date. Seems The Program Files config was being read-from while the AppData config was being written-to.

Simply deleting the "old" config file in Program Files fixed this for me. Also, I removed (from Program Files) the KeeAnywhere.Accounts.json file and the KeeAnywhereOfflineCache directory as it was clear they were old and out-of-date compared to the same file/directory in AppData.

**Comment by justinvoelker** [comment]
Same issue here. It appears to be conflicting config files (I have two: one in Program Files and one in AppData). The config in Program Files has the old KeeAnywhere version whereas the config in AppData has the newest, correct version of 1.6.0.0.

Personally, I believe my issue stems from previously using KeePass portable. When installing it normally I simply moved the config into the program directory. It looks like the config in the Program Files has not been updated in a while but the config in AppData is otherwise up-to-date. Seems The Program Files config was being read-from while the AppData config was being written-to.

Simply deleting the "old" config file in Program Files fixed this for me. I also removed (from Program Files) the KeeAnywhere.Accounts.json file and the KeeAnywhereOfflineCache directory as it was clear they were old and out-of-date compared to the same file/directory in AppData.

**Comment by ThirtySomething** [comment]
@Kyrodan unfortunately the trick with opening/closing the settings dialog did not work.

The hint from @justinvoelker was very good. I first used KeePass portable as well. Sometime in the past I switched to the installed version. I found two KeePass.config.xml files. From the location of KeePass portable I copied the file to the KeePass installation, removed the portable directory and everything worked as expected.

You can then close this issue.

**Comment by Kyrodan** [comment]
Clsiong as requested.
