### ISSUE TITLE
Dropbox: Registering a new account leads to exception

### ISSUE THREAD

**Issue by thamesvalley** [Kyrodan/KeeAnywhere#205]
Hi dear Mister Kyrodan,

I'm using keepass with your plugin KeeAnywhere with latest update.
I'm on Windows 10 x64 with latest updates too.
So, when I tried to add a Dropbox account I encountered a fatal error.
See attachements.
Thank you for your help.

[keeAnywhere bug when adding dropbox cloud details.txt](https://github.com/Kyrodan/KeeAnywhere/files/4083581/keeAnywhere.bug.when.adding.dropbox.cloud.details.txt)

![keeAnywhere bug when adding dropbox cloud](https://user-images.githubusercontent.com/44950574/72688474-e3bf5b00-3b07-11ea-9c94-6fd082f26a82.png)

More details : 
Authentication failed!

The supplied uri doesn't contain a fragment
Parameter name: redirectedUri
Dropbox.Api
   at Dropbox.Api.DropboxOAuth2Helper.ParseTokenFragment(Uri redirectedUri)
   at KeeAnywhere.StorageProviders.Dropbox.DropboxStorageConfigurator.Claim(Uri uri, String documentTitle)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__9.MoveNext()
Dropbox.Api.OAuth2Response ParseTokenFragment(System.Uri)

**Comment by Kyrodan** [comment]
Hi @thamesvalley 

from you attached TXT-File I can see:
* You have an a copy of Newtonsoft.Json.dll in your KeePass-Program-Folder
* You use KeeAnywhere as DLL-Distribution (I prefer the PLGX-Distribution)

Why do you need the Newtonsoft.Json.dll in your program folder? Is it used by another Plugin?
If not => please delete it from there and KeeAnywhere should work.
If yes => try to overwrite the DLL with the version from KeeAnywhere.

In general: try using the PLGX-Distribution for *all* plugins (instead of the DLL-Distribution). They are more version stable regarding new versions of KeePass.

**Comment by thamesvalley** [comment]
Hi,

 

I removed the dll. Replaced them with plgx file but the bug was still there.

I replaced the json in the keepass folder by another version (found in the KeeCloud directory) and it works now.

By the way, I have a request.

I use the cloud from Yandex.

Could you agree to make possible adding Yandex inside KeeAnywhere ?

 

Thank you for your help

**Comment by Kyrodan** [comment]
please open a new issue with your request for Yandex. I regularly collect votes for new storage providers and maybe implement them. I cannot promise, whether I will implement it, nor a timeframe.

Closing this issue => original problem has been solved.
