### ISSUE TITLE
[Google Drive] Shared database files

### ISSUE THREAD

**Issue by Adambean** [Kyrodan/KeeAnywhere#223]
Hello,

I'm not sure if this issue #93 is related as this mostly talks about the business G-Suite perspective with a subscription above the basic level, whereby Team Drives is a specific feature. (Regardless of whether you use Google File Stream or Google Backup & Sync.)

What we've tried so far is sharing the KBDX file (not a folder) from one account, then the receivers add the file as a shortcut to their drive. This makes it visible in KeeAnywhere, but cannot be opened. -- When you attempt this and insert any key (correct or not) you get a WebClient exception.

![image](https://user-images.githubusercontent.com/1108717/83948585-1dbe9e80-a816-11ea-86d6-77255072a740.png)

This is possibly related to what was said in issue #93 

> 1. Backup & Sync: There is not supported API to get the folders within "Computers". Except that, these folders are read-only. So the question is, whether it makes sense to support this or not, because you cannot save any changes. This is contrary to the spirit of this plugin, which was made to easily open and save ("sync") databases.
> 3. Shared Files: API is clear, but could also have the read-only issue.

Thanks for reading. :)

**Comment by ultraheroe** [comment]
I removed my account from Tools > KeeAnywhere settings... then login again to Google Drive and now it's running again perfectly

**Comment by Adambean** [comment]
Not sure that's really related to the issue?

**Comment by Lustrissime** [comment]
Hi, 

I get the same issue. I tried to remove and add again the Google Drive account in the plugin settings but it didn't change anything.

**Comment by cdebel2005** [comment]
It has something to do with the new way of Google to handle their options.   Before, they had "Add to my drive".  Now it's a "Add shortcut to my drive".   We had a workarround by pressing SHIFT-Z to add it to our drive, but now SHIFT-Z is also linked to Add Shortcut so we are back to the original problem.  The developer has to put some time on this.

**Comment by Tobias112358** [comment]
Hi! I'm running into this same issue - I'm trying to open a shared .kdbx file on Drive, but KeeAnywhere doesn't seem to like shortcuts and I can't access shared documents.
Don't suppose there are any plans to accommodate for this? If not, is there any workaround?

**Comment by Adambean** [comment]
Workaround: Get the newer Google Drive File Stream desktop client, which is now available for individuals not on G-Suite here.
https://support.google.com/drive/answer/7329379#zippy=%2Cdownload-install-google-drive-for-desktop

That'll allow you to open your KDBX on Google Drive without any KeePass plug-ins at all, and is also compatible with KeeAutoExec. The downside is you can only sign into one Google account at a time, but shortcuts to KDBX files shared with you work equally fine.

**Comment by Tobias112358** [comment]
Thank you! I ended up using Backup and Sync for Google Drive and added a shortcut to the shared database - it seems to sync well.
https://www.google.com/drive/download/

**Comment by Kyrodan** [comment]
Sorry for my late reply. There are plans, but currently I only have few time to implement things :-(

**Comment by Jackabomb** [comment]
This seems to be cropping up more often as Google gradually converts existing shares to the new shortcut format.
@HaydnHaines shared a bit more about this issue. [This info](https://github.com/Kyrodan/KeeAnywhere/issues/356#issue-1371621324) combined with [Google's memo](https://github.com/Kyrodan/KeeAnywhere/issues/339#issuecomment-1236819934) suggests this isn't limited to files and folders shared multiple users, but also may affect files that are all yours, if you accessed the file from different locations in the drive tree. Upon testing, this turned out to be true.

Workarounds:
- Use some other Google Drive client software on your device to expose the shared file(s), then open file normally in KeePass.
- [KPSync for Google Drive](https://www.kpsync.org/notices/sharedsec) can currently do this, but due to a security concern with their API token storage, you have to re-authorize every single session.

**Comment by Phil-ipp1** [comment]
Hello,
is there any roadmap to close this issue? It is currently blocking our teams to collaborate on password lists
