### ISSUE TITLE
Plugin incompatible with the current KeePass version

### ISSUE THREAD

**Issue by manugap** [Kyrodan/KeeAnywhere#302]
Hi

I have downloaded the last version of the plugin and copied it into the plugins folder but when I start kee pass I keep getting this message (see attached image for full dettails) 
"The Following plugin is not compatible with the current KeePass version: C\:Programmi_Personali\KeePass2\Plugins\KeeAnywhere-2.0.3.plgx"

Any idea on what could be the problem? could it be because of the portable version?
thanks for the support!

KeePass version: Portable (2.48.1)
KeeAnywhere plugin version:  2.0.3
![KeeAnywhereError](https://user-images.githubusercontent.com/86725770/123967144-53e93600-d9b6-11eb-897b-7f3b3174d73e.JPG)

**Comment by cacophobe** [comment]
From my recent experience with KeePass 2.55 on Windows 11, it requires that KeePass is started with 'Admin' or 'root' privileges when initializing the plugin for the first time. My guess is it's because it needs access to the system's secure credentials storage. Once you have the credentials of your cloud provider authenticated and saved, you can start KeePass normally.
