### ISSUE TITLE
Using from an "untrusted" computer? [question]

### ISSUE THREAD

**Issue by RayDeanTech** [Kyrodan/KeeAnywhere#316]
Just curious....

If I use this on an "untrusted" computer, like from a library or work, would the IT Admins be able to "gain access" to the DB once opened...

1. Does the KeePass DB get copied (permanently/temporarily) to the local file system during the unlock process?
2. Is the KeePass DB available "in memory" to whatever scanner might be running on said computer, in such a way that it could be exploited by an Admin (antivirus, IT surveillance, etc. etc. etc.)?

I'm just interested in how it works, looking forward to using this plug-in, thanks!

**Comment by Jackabomb** [comment]
This doesn't really belong in this repo. It isn't a KeeAnywhere question so much as a KeePass question. However, I would direct you to the KeePass website page on [Security](https://keepass.info/help/base/security.html). They may have answered your questions there. In particular, [Process Memory Protection](https://keepass.info/help/base/security.html#secmemprot) and [Specialized Spyware](https://keepass.info/help/base/security.html#secspecattacks) look relevant.

**Comment by Jackabomb** [comment]
@NamedArray I'm sorry for my brusque reply last year. It is a good and valid question. It's true that the question is more about Keepass in general, and I still believe the links I shared address the questions (for anyone else who has the same questions).

But I didn't have to be so short/blunt in the way I said so. Please accept my apology.

You may not see this, but if anyone else comes here, please know my previous comment is a good example of how *not* to treat innocent newcomer questions.

**Comment by NamedArray** [comment]
@Jackabomb No damage done, my friend.  The reason I asked was because I was working for a company that was into Digital Intelligence, and they monitored staff with SSL inspection, myself included.  I had access to the Netskope logs... I saw my KeePass DB filename was in the logs... I could see that KeePass was opening my *.kdbx file via KeeAnywhere in my personal cloud storage.

Anyway, I wasn't too keen on what they were doing.  I felt like the company I was working for had access to my bank accounts.  I no longer access my personal KeePass file at a workplace :)

Anyway, yes, this should have been posted in the discussion section, and I suppose it can be closed.
