### ISSUE TITLE
Open or Save in hubiC doesn't work

### ISSUE THREAD

**Issue by boushi69** [Kyrodan/KeeAnywhere#34]
Whatever I'm trying to open or save a new database in hubiC, the same error is raised.
See attached files.
The second screenshot is when i'm trying to continue for saving.

![keeanywhereerror-01](https://cloud.githubusercontent.com/assets/3799289/15282996/81468248-1b47-11e6-9a69-31749c450690.png)
![keeanywhereerror-02](https://cloud.githubusercontent.com/assets/3799289/15282995/81418d60-1b47-11e6-80f9-737fe4dfe1f6.png)

**Comment by Kyrodan** [comment]
Hi @boushi69 ,

could you please attach the complete "Détails" of the exception from the second screenshot.

I have an idea why this happens:
Do you have very large files in your hubiC root folder? In your case a file with nearly 100GB in size? If yes, then there is a bug due to an invalid documentation which states a maximum file size of 2 GB.

Regards,
Daniel

**Comment by alphamax** [comment]
Fix tested in V1.1.
Worked like a char for me.
Thanks,

**Comment by boushi69** [comment]
Sorry I didn't see your comments.
It works perfectly with V1.1.
Thank you!
