### ISSUE TITLE
Old keeanywhere Versions 

### ISSUE THREAD

**Issue by FastByte23** [Kyrodan/KeeAnywhere#368]
My company still uses Keepass 2.42.1 I would also like to use keeanywhere here, where can I find older versions that work with 2.42.1.

**Comment by Jackabomb** [comment]
According to the changelog, KeeAnywhere 1.5.1 is the last compatible version.
[1.5.0 required KP 2.40+](https://github.com/Kyrodan/KeeAnywhere/blob/master/CHANGELOG.md#150-2018-09-20)
[1.6.0 required KP 2.43+](https://github.com/Kyrodan/KeeAnywhere/blob/master/CHANGELOG.md#160-2020-01-08)
Old releases are available from the [Releases page](https://github.com/Kyrodan/KeeAnywhere/releases). You can get there from the main repo sidebar by clicking the "Releases" header or the "+14 releases" under the current latest.

Keep in mind that 1.5.1 was released over 4 years ago. If you do use it, I'd at least recommend looking over the changelog bugfixes since 1.5.1, because all those bugs may still be present in 1.5.1. In particular, it looks like 1.6.0 -> 2.0.0 fixed a lot of problems with Google Drive auth. That's when Kyrodan switched the browser used for Oauth from internal -> system default.

Best of luck!

**Comment by Kyrodan** [comment]
Have you tried latest PLGX-Release? Perhaps this works with this KeePass
Version.

Jackabomb ***@***.***> schrieb am Mi., 4. Jan. 2023, 19:42:

**Comment by FastByte23** [comment]
> Have you tried latest PLGX-Release? Perhaps this works with this KeePass Version.

Hello, 
I used the latest PLGX again, but had no success, see screenshots. 
And the old plugin does not let me access Google. 

![1](https://user-images.githubusercontent.com/33317427/210744505-447be244-1d8b-4c65-acd7-65c960457293.JPG)
![2](https://user-images.githubusercontent.com/33317427/210744512-5fc90612-b629-4772-8918-bdb5290d8aef.JPG)
