### ISSUE TITLE
keepass version 2.34

### ISSUE THREAD

**Issue by westsyde** [Kyrodan/KeeAnywhere#39]
Since version 2.34 i haven't been able to connect my Dropbox account to the KeeAnywhere plugin. It worked perfectly on version 2.33 and connected instantly however with version 2.34 i cant make the connection too Dropbox. It fails to assign Dropbox to the KeeAnywhere Configuration area.

Version 2.34 now has a plugin directory whereas 2.33 the KeeAnywhere folder went straight into the root directory so I'm wondering if it has something to do with this. If I put KeeAnywhere in the root directory now I cant access KeeAnywhere from the keepass tools menu so KeeAnywhere has to go in the plugin folder now to become visible in the tools menu. 

Hope this is a quick fix. Really like KeeAnywhere

**Comment by Kyrodan** [comment]
Hi @westsyde,

KeeAnywhere should work fine with KeePass 2.34. Do you use the PLGX-Distribution? If yes, it should work in plugins directory and in root directory of KeePass installation. You should see "KeeAnywhere settings..." menu item in "Tools" menu. That indicates the plugin could generally be leaded.

If you use DLL-Distribution, please try PLGX-Distribution: just put the PLGX-File in your plugins folder. DLL-Distribution may (but shouldn't) fail on 2.34.

Regarding Dropbox registration: currently it does not work (independent of 2.34), maybe Dropbox has changed something. I will file an issue for that and link it.

**Comment by Kyrodan** [comment]
See #40.

**Comment by westsyde** [comment]
Thanks for the prompt reply.

I was using the *.dll version and swapped to the *.plgx after your reply but I still have the issue (bug) reported in [#40](https://github.com/Kyrodan/KeeAnywhere/issues/40) as above. I suspect my issue is associated with that.

Not sure how I connected Dropbox to version 2.33 though given you're saying its not a version 2.34 related issue ??

Hopefully a solution isn't to far away. Thanks.

**Comment by Kyrodan** [comment]
It's due to a change on Dropbox side: registering a Dropbox account currently fails on every KeePass version.

**Comment by Kyrodan** [comment]
New release is out, please test it.

**Comment by westsyde** [comment]
Awesome. It appears that both versions work now.

One other thing, I assume there's an advantage/benefit in using the *.plgx over *.dll version ??
Can you briefly explain the differences. Thanks

**Comment by Kyrodan** [comment]
DLL-Distribution is precompiled by me against the lowest supported KeePass version (2.31) and my .Net-Version.
PLGX contains source code that is compiled on *your* machine with *your* installed .Net-Framework and the exact version of *your* KeePass.

The main goal of this new plugin format was to support platform independency supporting Windows and Linux with Microsoft .Net and Mono. 

Currently I only support Windows with Microsoft .Net so there is no deep technical reason to prefer one over the other. 
Nevertheless I recommend to use PLGX-Distribution: 
* it's the de-facto recommended way of the author of KeePass and is accepted by many other plugin developers
* you only have to drop exactly one file to your KeePass plugin folder - this is easier (for less experienced users) than unzipping a folder. 
* brand new: a Chocolatey-Package [keepass-plugin-keeanywhere](https://chocolatey.org/packages/keepass-plugin-keeanywhere/) has been created which uses the PLGX due to this simplicity

**Comment by westsyde** [comment]
Thanks @Kyrodan
