### ISSUE TITLE
Google Drive - limit access to KeeAnywhere files only and not the whole drive (like Dropbox-restricted)

### ISSUE THREAD

**Issue by khelge** [Kyrodan/KeeAnywhere#398]
Could you change the permission requested by the addon when choosing google drive? Currently it seems like it requests access to my whole account, while you can limit the request to only access a specific folder or files created by the addon

https://www.googleapis.com/auth/drive.appfolder Allows access to the Application Data folder
https://www.googleapis.com/auth/drive.file Per-file access to files created or opened by the app. File authorization is granted on a per-user basis and is revoked when the user deauthorizes the app.

Or something like this: https://stackoverflow.com/questions/58041597/use-google-drive-from-an-app-with-a-folder-limit-like-dropbox

**Comment by ElizaZadura** [comment]
I just got a new PC, and adding a Google drive is blocked, don't know how to get around it. I'm still connected and using my Google drive storage (and the keypass key file that's stored there) on my laptop, with no problems.

**Comment by Jackabomb** [comment]
I'm not the developer, but I do have two use cases that need the broader access level:

- I share a database with someone who uses an iPhone, using KeePassium. The KeePassium app appears to have the `drive.file` permission, because that iPhone can only see items in the "KeePassium" folder of the shared Google Drive, and even then only those files and folders that the KeePassium app has created. (So that user can't see the 10 backups that KeeAnywhere creates). For us to be able to interoperate, this means KeeAnywhere has to have access to the whole drive. KeePassium can't break out of its "jail", so KeeAnywhere has to reach in.
- Uploading a Keepass database to your Google Drive in the web interface may not work with apps that have the more limited scope. I think the apps wouldn't be able to see the newly uploaded file.

**Comment by Kyrodan** [comment]
Implementation: Using `drive.file` permission. 
Jackabomb's comment completely is completely right. Currently we have no option to create folders from KeeAnywhere, so saving is restricted to "root" folder. But maybe this helps to circumvent #393
