### ISSUE TITLE
Keep database files history

### ISSUE THREAD

**Issue by vovodroid** [Kyrodan/KeeAnywhere#45]
Hi,

I'm using Dropbox as storage provider and payed attention that though Dropbox keeps deleted files for one month, but no such history is available for KeeEnywhere data file.
Probably file is not deleted, but rewritten.

Can you change KeeAnywhere behavior to allow keeping history (may be create new temporary file, delete old one and then rename)? Google Drive also has thrash bin, so such approach can be used for it too.
Or, may be, rename old file to name consisting time stamp before creation of new, and keep configurable number of files.

Thanks.

**Comment by Kyrodan** [comment]
Hi @vovodroid,

you are right, KeeAnywhere does not delete a file, it simply overwrites it. And this is the expected behavior. The reasons:
* I don't want to litter "Deleted Files"
* Dropbox keeps a file history and if I delete a file and recreate it then it's simply a new file with no history.

What do you want to achieve with keeping "deleted copies"? Maybe you want to restore to an older maybe accidently overwritten version. And especially for this Dropbox keeps file hostory. Right-Click a file in Dropbox, the context menu opens. Choose "Earlier Versions" and a screen appears with a history of every single "save".
Does this help you? 

> Or, may be, rename old file to name consisting time stamp before creation of new, and keep configurable number of files.

I already have a similar function in mind: a kind of "backup" enhancement which keeps a defined number of copies.

Regards,
Daniel

**Comment by vovodroid** [comment]
> Dropbox keeps file history

Ahh, you are right, great!
