### ISSUE TITLE
Access to owncloud

### ISSUE THREAD

**Issue by mattekure** [Kyrodan/KeeAnywhere#47]
I am looking for access to ownCloud (https://owncloud.org/).

While owncloud and keepadd do support webdav I am having significant difficulty getting them to communicate properly.

**Comment by Kyrodan** [comment]
Hi @mattekure,

what are the concrete Problems with OwnCloud and WebDav? As this is generlly supported by both, you have in theory one of the best solutions - out of the box.

I'm unsure whether it makes sense to implement this request: OwnCloud is far beyond a simple system and as user you have to know at least your servers URL - and this must then be supported from KeeAnywhere. Currently this is out of scope because KeeAnywhere focuses on simplicity and the "it just runs" paradigma. Additionally I don't want to invest in, run and maintain my own development OwnCloud-Server.

Regards,
Daniel

**Comment by mattekure** [comment]
In theory,  you are right, and that is exactly the scenario I hoped for when initially setting up keepass and owncloud to work together.

However, there is something incompatible between the webdav implementations of keepass and owncloud.  Using just keepass, I am able to open the webdav hosted file successfully.  However, any attempt to save changes fails.  I dont think this is unique to me as there are numerous posts on both keepass and owncloud forums of people expressing difficulty with getting it to work.  

I do understand if you consider this out of scope for your project.  Thank you for your consideration.
