### ISSUE TITLE
Cache databases for disconnected (offline) usage

### ISSUE THREAD

**Issue by Kyrodan** [Kyrodan/KeeAnywhere#5]
Cache databases for disconnected (offline) usage

**Comment by dnauck** [comment]
+1

**Comment by vmalguy** [comment]
It would be awesome if the cache database could be merge with the online version when the connection is back.

**Comment by Kyrodan** [comment]
That was the plan: a complete transparent mechanism like in
KeePass2Android. I already investigated a little bit and it's more
complicated than I thought: the KP2A Code could not be adapted because it
is on a Level more closer to the core.

But I continue working on this.

vmalguy <notifications@github.com> schrieb am Do., 28. Jan. 2016 09:42:

**Comment by Steampower** [comment]
in general, it would be great if the plugin can be used behind a proxy server... I want to use keepass @ work and store the database in the cloud, so i can use it also at home, on my mobile etc.

but anyway - thanks for the great tool, at home it's working very nicely :)
- Benjamin

**Comment by Kyrodan** [comment]
Hi @Steampower,

thank for your feedback. See #16 for proxy support. Currently it's not planned for short-term (due to technical reasons). But I plan to implement it long-term.

Regards,
Daniel

**Comment by auanasgheps** [comment]
Yes, please. At least basic caching for emergency offline use!

**Comment by Kyrodan** [comment]
Waiting for reply: 
https://sourceforge.net/p/keepass/bugs/1575/

**Comment by vovodroid** [comment]
May be on each save also just save local copy to file for simplicity? (like File/Save as../Save copy to File)

**Comment by Kyrodan** [comment]
@vovodroid,
yes that's the plan. Here is a preview screenshot from settings dialog:
![2017-03-20 10_09_20 - keepass](https://cloud.githubusercontent.com/assets/355178/24093700/7694fae0-0d55-11e7-979d-9bbb56b7a154.png)

**Comment by CumpsD** [comment]
Can't you already do this today? I have this setup already.

You have a local kdbx which you open, and you use a KeePass Trigger to sync with the cloud kdbx file on save, KeeAnywhere then kicks in because of the url format and it does the save.

This way you always have access to the local version. It's a variation of http://keepass.info/help/kb/trigger_examples.html#dbsync

**Comment by Kyrodan** [comment]
@CumpsD ,
what do you mean concrete: Offline Cache or Auto-Backup?
In general you are right: you already can do something similar. But I'd like to go a little bit further.

The main differences are:
* AutoBackup uses Cloud-Copy-Functions so you do not have to "Upload"/send the database again for backup (like all backup plugins do). Version history of cloud files are preserved, if the cloud provider supports it.
* Offline-Caching recognizes, if your connection is back again on next usage of the database (open/read/write). So the "local" changes get synced to cloud, as soon as possible (without the need of useless traffic). With triggers you cannot achieve this behavior. This function has a kind of logic to determine the need of a sync.
* Triggers are good but a little bit complicated to setup. Therefore I use them, I hate their UI. It's much easyer to mark a checkbox :-)

**Comment by CumpsD** [comment]
I think if I had to classify it, it would be somewhere in between. I agree your suggestion goes beyond what KeePass can do today, especially with the detection of online status. Re-thinking about it, your proposal is indeed a nice user experience and will probably help keep a lot of people more safe with regard to backups.

For reference, what I currently have:
- .kdbx file locally
- .kdbx file on cloud provider A
- .kdbx file on cloud provider B
- .kdbx file on home NAS

Day to day usage (at home and on the road) I open the local kdbx file. On Save there is a trigger which syncs it with provider A, B and if the NAS is reachable also with the NAS. KeeAnywhere helps me to sync with provider A and B thanks to simply specifying the url to them (and not needing a username/pass since KeeAnywhere takes care of these).

This gives me 
 * an (as good as) up to data local kdbx which also works when I am offline.
 * a master copy on provider A and B to be used as sync between various local copies.
 * an extra backup on a home NAS

Which satisfies my needs ;)

**Comment by koenmetsu** [comment]
@Kyrodan can you give us a status on how this is progressing? I'd love this functionality.

**Comment by skironDotNet** [comment]
I think the was KeePass2Android does it based on my observation, is it download the file to local, you can work with file or not. in case of an offline it just won't download but you can still use the current version. Once you done working with the DB and close the app lock the DB it uploads the file back to "cloud". I just don't know how it handles the case when you worked with DB on Android but can upload, then workded on PC and uploaded, then Android do what? Download the file, and sync locally?

Either way for simple use case I wish KeePass download locally, and upload only on lock/exit. because I'm using QuickUnlock plugin to work same as on Android, but the problem is once I lock the DB, and I'm in "quickunlock mode" I would expect KeePass to just unlock local file, but it does re-download, makes no sense in case of single tenant use. I mean how many people will use it by multi-device, or multi-people extensively? It would be nice while KeePass is running and just just lock the DB to unlock using local cached/file, why to re-download after each lock. What if I need to lock my PC grab a coffee, and 5 min later comeback, why to re-download?
