### ISSUE TITLE
KeePass hangs with KeeAnywhere first time

### ISSUE THREAD

**Issue by Barleyman** [Kyrodan/KeeAnywhere#69]
I'm using KeePass 2.3.5 (Windows 10) and KeeAnywhere 1.3.1.0. 

I can open database from google drive account OK but minimizing KeepAss to tray will freeze it. If I exit KeepAss from file menu without minimizing it and restart it, it'll work fine. So it appears this is a problem running KeeAnywhere 1st time or perhaps having to cancel the default database and opening a new one from cloud location.

**Comment by Kyrodan** [comment]
This is a duplicate to #63 and is related to #68: These will be fixed in next release.

Workaround:
Do *not* open Cloud File Browser, Donation Form or Account Creation Form prior minimizing to tray.
It works fine, if you open a cloud based database from Recent File List.

I'm sorry for your inconvenience

**Comment by Barleyman** [comment]
I did actually check the issue list, "account creation" didn't connect in my mind. By default the previous database is opened so if you exit from file menu once, the problem goes away.
