### ISSUE TITLE
how to sync with dorpbox without loosing data?

### ISSUE THREAD

**Issue by badplay** [Kyrodan/KeeAnywhere#73]
hi i want to have my local db saved in dropbox but without loosing data if 2 or 3 pcs use keepass db too

so how i can do this ??? sync directly on dropbox is i think not the best or ???

and second how i can set up a automatic sync ???

**Comment by Kyrodan** [comment]
The best way is to sync all PC's local copies with Dropbox. See details here: http://keepass.info/help/v2/sync.html

If you use all of the PC's by yourself and you do not do changes at the same time on several machines, then you also can open and save the databases directly with KeeAnywhere: KeePass takes care, whether a database has changed since last load and asks to Merge, Keep Local Changes or Use Remote Changes only.
