### ISSUE TITLE
Error when opening KeeAnywhere Settings 1.4.0

### ISSUE THREAD

**Issue by Gummientchen** [Kyrodan/KeeAnywhere#86]
Hi, I get the following error when trying to open the settings:

Fresh install of KeePass 2.35, no other plugins installed. Version 1.2.0 works.

```
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Wert 0 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei KeeAnywhere.Forms.SettingsForm.InitGeneralTab()
   bei KeeAnywhere.Forms.SettingsForm.OnFormLoad(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
KeePass
    Assembly-Version: 2.35.0.20042.
    Win32-Version: 2.35.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1586.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
KeeAnywhere
    Assembly-Version: 1.4.0.0.
    Win32-Version: 1.4.0.0.
    CodeBase: file:///C:/Users/sbl/AppData/Local/KeePass/PluginCache/cLZDQB9JIsfJcF8CeSqm/KeeAnywhere.dll.
----------------------------------------
System.Net.Http.Primitives
    Assembly-Version: 4.2.29.0.
    Win32-Version: 4.2.29.0.
    CodeBase: file:///C:/Users/sbl/AppData/Local/KeePass/PluginCache/cLZDQB9JIsfJcF8CeSqm/System.Net.Http.Primitives.DLL.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 10.0.0.0.
    Win32-Version: 10.0.2.20802.
    CodeBase: file:///C:/Users/sbl/AppData/Local/KeePass/PluginCache/cLZDQB9JIsfJcF8CeSqm/Newtonsoft.Json.DLL.
----------------------------------------
Microsoft.Graph.Core
    Assembly-Version: 1.4.0.0.
    Win32-Version: 1.4.0.0.
    CodeBase: file:///C:/Users/sbl/AppData/Local/KeePass/PluginCache/cLZDQB9JIsfJcF8CeSqm/Microsoft.Graph.Core.DLL.
----------------------------------------
CommonMark
    Assembly-Version: 0.1.0.0.
    Win32-Version: 0.1.0.0.
    CodeBase: file:///C:/Users/sbl/AppData/Local/KeePass/PluginCache/cLZDQB9JIsfJcF8CeSqm/CommonMark.DLL.
----------------------------------------
Microsoft.mshtml
    Assembly-Version: 7.0.3300.0.
    Win32-Version: 7.0.3300.0.
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll.
----------------------------------------
KeePass.XmlSerializers
    Assembly-Version: 2.35.0.20042.
    Win32-Version: 2.35.0.20042.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.
```

**Comment by Kyrodan** [comment]
Hi @Gummientchen ,

The "Number of Copies to Keep" for Automatic Backup seems to be wrong.
To workaround: 
* Close KeePass
* open your KeePass.config.xml (from "C:\Users\{yourusername}\AppData\Roaming\KeePass" if KeePass is installed)
* Search for "BackupCopies"
* Set the value for this to something greater than 0 (default = 10)
* Save file and restart KeePass

If you do not have a proper `KeeAnywhere.Plugin` Item in Config, then copy this default section within `Configuration/Custom` of this XML file:
```
<Item>
   <Key>KeeAnywhere.Plugin</Key>
   <Value>{"IsOfflineCacheEnabled":false,"IsBackupToLocalEnabled":false,"IsBackupToRemoteEnabled":false,"BackupCopies":10,"AccountStorageLocation":"LocalUserSecureStore"}</Value>
</Item>
```

I will implement a check for this special issue in the next release.

**Comment by moisty70** [comment]
So. Saving to cloud is not working. Is it?

**Comment by Kyrodan** [comment]
@moisty70 
What do you mean with "Saving to cloud is not working. Is it?"
This bug has been fixed in Version 1.4.1.

**Comment by moisty70** [comment]
Got an error when saving to Google Drive

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid chars in path.
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.36.0.17315
    Win32 Version: 2.36.0.0
    CodeBase: file:///C:/MOI/instalados/KeePass2/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
GoogleSyncPlugin
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/GoogleSyncPlugin.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.2.20802
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Microsoft.Graph.Core.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.36.0.17315
    Win32 Version: 2.36.0.17315
    CodeBase: file:///C:/MOI/instalados/KeePass2/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/Google.Apis.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Google.Apis
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/Google.Apis.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.16.0.596
    Win32 Version: 1.16.0.596
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/Google.Apis.Drive.v3.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/bjFVhxIY8AzWirB94gEv/Newtonsoft.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.26.2.869
    Win32 Version: 1.26.2.869
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.26.2.0
    Win32 Version: 1.26.2.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.26.2.0
    Win32 Version: 1.26.2.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.26.2.0
    Win32 Version: 1.26.2.0
    CodeBase: file:///C:/Users/moi/AppData/Local/KeePass/PluginCache/aMDUtX6RqINZaICHbvgG/Google.Apis.Auth.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Kyrodan** [comment]
Do you hava any special characters in your Account Name? If yes => see Bug #91

**Comment by moisty70** [comment]
Wow. Works now. Thanks
