### ISSUE TITLE
GDrive: Umlaut in Account name leads to Exception

### ISSUE THREAD

**Issue by Stimmenhotel** [Kyrodan/KeeAnywhere#91]
If I log into my G-Drive account I will get a error, since I have umlauts(mutation, Ü. Ä, Ö) in my name.
I think this is the fault, since I have a ü in my name and KeeAnywhere gives the error "Invalid chars in path".

I use both the latest version. (Keppass 2.36, KeeAnywhere 1.41)
Using windows, the plugin is the .plgx version.
I am on Windows 10.

![image](https://user-images.githubusercontent.com/15821524/27134130-e3d617ee-5114-11e7-9679-a71dde1399e0.png)
[KeeAnywhere.txt](https://github.com/Kyrodan/KeeAnywhere/files/1074673/KeeAnywhere.txt)

**Comment by Kyrodan** [comment]
Thanks for reporting.

Workaround: Rename your Account not using umlaut, see https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#rename-an-account

**Comment by Kyrodan** [comment]
Hi @Stimmenhotel,
I can't reproduce this issue. I checked several variants with Umaluts in Names, Folders etc.
Could you please try to analyze the concrete char causing this issue?

**Comment by Stimmenhotel** [comment]
Okay, I have added my GDrive account to keeanywhere.
No problems with this. Mail contains no umlauts. But account name has one it it (ü).

If I now want to open a file from my gdrive the exception gets thrown.
Don't know what path the plugin tries to access at all.

[error.txt](https://github.com/Kyrodan/KeeAnywhere/files/2152746/error.txt)

![error](https://user-images.githubusercontent.com/15821524/42133808-0aada13c-7d30-11e8-8866-e3bd52b413b5.PNG)

**Comment by marcomsousa** [comment]
I have the same error in my machine:
![Captura](https://user-images.githubusercontent.com/1110889/70611757-00fa3300-1c06-11ea-9fd1-c609aeb2f40f.PNG)
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid chars in path.
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3460.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.0
    CodeBase: file:///C:/Users/martm226/Downloads/KeePass/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.5.1.0
    Win32 Version: 1.5.1.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.18739
    CodeBase: file:///C:/Users/martm226/Downloads/KeePass/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.34.0.1239
    Win32 Version: 1.34.0.1239
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/martm226/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by Kyrodan** [comment]
@marcomsousa could you please try this unstable test-build: https://github.com/Kyrodan/KeeAnywhere/files/4054011/KeeAnywhere-1.7.0-unstable.plgx.zip

I have extended the error message to report more detailed information of the root-cause.
Could you please report back, what this message reports? I am especially interested in all the line breaks (exact message).

**Comment by peter149** [comment]
Vers. 1.7.0 works fine, because detailed information shows name of files on your GDRIVE with Invalid characters. After removing this files to another dir, the error  is gone and  opening of database is successfull.

**Comment by Thunderhawk2001** [comment]
Thanks a lot ! Had the same problem and it wasn't a Umlaut, but maybe the "&" sign in the original file name.
I moved the file, and it's working again.

**Error Message with Version 1.7.0**
![image](https://user-images.githubusercontent.com/14139482/93015153-750fa000-f5b7-11ea-9e74-81081d2bf69a.png)

**File in Google Drive:**
![image](https://user-images.githubusercontent.com/14139482/93015158-7d67db00-f5b7-11ea-812c-643b365ab948.png)



Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentException: Invalid char in path 'Kopie von Resto Shaman Trinket & Azerite Calculator
' at position 51: 10 (decimal)
   bei KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   bei KeeAnywhere.CloudPath.GetExtension(String path)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
